version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "starwars-timeline-tweet"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dw6g2pvvlkx"
s3_prefix = "starwars-timeline-tweet"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
